name = "webauthntest"
compatibility_date = "2026-01-19"

main = "src/worker.js"

# Serve static UI from ./public (Workers + Assets)
assets = { directory = "public", binding = "ASSETS" }

# D1 binding (create DB then update database_id)
[[d1_databases]]
binding = "DB"
database_name = "webauthntest"
database_id = "e9be8827-afdc-4d3d-ab4a-ad504b1c8ba5"
